# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[override]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[override]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


[[override]]
  name = "github.com/dgrijalva/jwt-go"
  version = "3.2.0"

[[override]]
  branch = "master"
  name = "github.com/gin-contrib/static"

[[override]]
  branch = "master"
  name = "github.com/gin-gonic/gin"

[[override]]
  name = "github.com/itsjamie/gin-cors"
  version = "1.0.0"

[[override]]
  name = "github.com/mongodb/mongo-go-driver"
  version = "0.0.6"

[[override]]
  name = "github.com/patrickmn/go-cache"
  version = "2.1.0"

[[override]]
  branch = "master"
  name = "github.com/streadway/amqp"

[[override]]
  branch = "master"
  name = "golang.org/x/crypto"

[[override]]
  name = "gopkg.in/go-playground/validator.v9"
  version = "9.17.1"

[[override]]
  name = "github.com/stretchr/testify"
  branch = "master"

[prune]
  go-tests = true
  unused-packages = true
